---
title: "Untitled"
author: "Srikanth Aravamuthan"
date: "8/4/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

knitr::opts_chunk$set(
  echo = FALSE,
  # cache = TRUE, 
  message = FALSE,
  warning = FALSE, 
  fig.width = 10
)

library(tidyverse)
library(plotly)

```

```{r}
initial.susceptible <- 1500
initial.infected <- 10

r0 <- 1.5
exogenous.shocks <- "Yes"
frequency.exogenous.shocks.per.day <- 7
new.infections.per.shock <- 10
days.incubation <- 3
time.to.recovery <- 14
per.asymptotics.advancing.to.symptoms <- 0.3
symptom.case.fatality.ratio <- 0.0005
frequency.screening <- "Weekly"
test.sensitivity <- 0.8
test.cost <- 25
test.specificity <- 0.98
time.to.return.fps.from.isolation <- 3
confirmatory.test.cost <- 100

```

```{r}
num.exogenous.shocks <- case_when(
  exogenous.shocks == "Yes" ~ 1,
  exogenous.shocks == "No" ~ 0
)
cycles.per.day <- 3
frequency.exogenous.shocks <- cycles.per.day*frequency.exogenous.shocks.per.day
cycles.per.test <- case_when(
  frequency.screening == "Daily" ~ 1*cycles.per.day,
  frequency.screening == "Every 2 Days" ~ 2*cycles.per.day,
  frequency.screening == "Every 3 Days" ~ 3*cycles.per.day,
  frequency.screening == "Weekly" ~ 7*cycles.per.day,
  frequency.screening == "Every 2 Weeks" ~ 14*cycles.per.day,
  frequency.screening == "Every 3 Weeks" ~ 21*cycles.per.day,
  frequency.screening == "Every 4 Weeks" ~ 28*cycles.per.day,
  frequency.screening == "Symptoms Only" ~ 99999999999
)
rho <- 1/(time.to.recovery*cycles.per.day)
sigma <- rho*(per.asymptotics.advancing.to.symptoms/(1-per.asymptotics.advancing.to.symptoms))
beta <- r0*(rho+sigma)
delta <- (symptom.case.fatality.ratio/(1-symptom.case.fatality.ratio))*rho
theta <- 1/(days.incubation*cycles.per.day)
mu <- 1/(cycles.per.day*time.to.return.fps.from.isolation)

```

```{r}
n.cycle <- 240

mat <- matrix(c(0,initial.susceptible,0,0,initial.infected,0,0,0,0), nrow = 1)
mat <- rbind(mat,
             c(1,
               max(0,mat[1,2]*(1-beta*(mat[1,5]/(mat[1,2]+mat[1,5]+mat[1,4])))+mat[1,3]*mu),
               max(0,mat[1,3]*(1-mu)),
               max(0,mat[1,4]*(1-theta)+ beta*(mat[1,2]*mat[1,5]/(mat[1,2]+mat[1,5]+mat[1,4]))),
               max(0,mat[1,5]*(1-sigma-rho)+mat[1,4]*theta),
               max(0,mat[1,6]*(1-delta-rho)+(mat[1,5]+mat[1,7])*sigma),
               0,
               max(0,mat[1,8]+(mat[1,5]+mat[1,6]+mat[1,7])*rho),
               max(0,delta*mat[1,6]+mat[1,9]))
             )

superspreader.event <- 0
superspreader.event <- c(superspreader.event, 
                         (1:n.cycle %% frequency.exogenous.shocks == 0)*num.exogenous.shocks)

for(i in 2:n.cycle) {
  mat <- rbind(mat,
             c(i,
               max(0,mat[i,2]*(1-beta*(mat[i,5]/(mat[i,2]+mat[i,5]+mat[i,4])))+mat[i,3]*mu-mat[i-1,2]*(1-test.specificity)/cycles.per.test-superspreader.event[i+1]*new.infections.per.shock),
               max(0,mat[i,3]*(1-mu)+mat[i-1,2]*(1-test.specificity)/cycles.per.test),
               max(0,mat[i,4]*(1-theta)+ beta*(mat[i,2]*mat[i,5]/(mat[i,2]+mat[i,5]+mat[i,4]))+superspreader.event[i+1]*new.infections.per.shock),
               max(0,mat[i,5]*(1-sigma-rho)+mat[i,4]*theta-mat[i-1,5]*test.sensitivity/cycles.per.test),
               max(0,mat[i,6]*(1-delta-rho)+(mat[i,5]+mat[i,7])*sigma),
               max(0,mat[i,7]*(1-sigma-rho)+mat[i-2,5]*test.sensitivity/cycles.per.test),
               max(0,mat[i,8]+(mat[i,5]+mat[i,6]+mat[i,7])*rho),
               max(0,delta*mat[i,6]+mat[i,9]))
             )
}

mat <- cbind(mat, superspreader.event)

```

```{r}
names.df <- c("Cycle","Susceptible","FP","Exposed","Asympt","Symptoms","TP","Recovered","Dead","Superspreader Event")
df <- 
  mat %>% 
  as_tibble() %>% 
  rename_all(~names.df) %>% 
  mutate(`Persons Tested` = (lag(Susceptible,1,NA)+lag(Exposed,1,NA)+lag(Asympt,1,NA))/cycles.per.test,
         `Total TPs` = lag(Asympt,2,NA)*test.sensitivity/cycles.per.test,
         `Total FPs` = lag(Susceptible,2,NA)*(1-test.specificity)/cycles.per.test,
         `Total TNs` = lag(Susceptible,2,NA)*test.specificity/cycles.per.test,
         `Total FNs` = lag(Exposed,2,NA)+lag(Asympt,2,NA)*(1-test.sensitivity)/cycles.per.test) %>% 
  mutate(Day = Cycle/cycles.per.day,
         `True Positive` = TP,
         Symptoms = Symptoms,
         `False Positive` = FP,
         Total = TP+Symptoms+FP) %>% 
  mutate(`New Infections` = lag(Asympt,1,NA)*beta*lag(Susceptible,1,NA)/(lag(Susceptible,1,NA)+lag(Exposed,1,NA)+lag(Asympt,1,NA)),
         `New Infections` = ifelse(Cycle>1,
                      `New Infections`+pmin(`Superspreader Event`*new.infections.per.shock,lag(Susceptible,1,NA)),
                      `New Infections`),
         `New Infections` = ifelse(is.na(`New Infections`),0,`New Infections`),
         `Cumulative Infections` = cumsum(`New Infections`),
         `%Cumulative Infections` = `Cumulative Infections`/initial.susceptible)

```

```{r}
sum.stat <- 
  df %>% 
  summarize(`Total Persons Tested in 80 days` = sum(`Persons Tested`, na.rm = TRUE),
            `Total Confirmatory Tests Performed` = sum(`Total TPs`, na.rm = TRUE) + sum(`Total FPs`, na.rm = TRUE),
            `Average Isolation Unit Census` = mean(`Total`, na.rm = TRUE),
            `Average %TP in Isolation` = 1-(mean(`False Positive`, na.rm = TRUE)/mean(`Total`, na.rm = TRUE)),
            `Total testing cost` = `Total Persons Tested in 80 days`*test.cost+`Total Confirmatory Tests Performed`*confirmatory.test.cost,
            `Total Infections` = last(`Cumulative Infections`))

```

```{r}
df %>% 
  select(Day, `True Positive`, Symptoms,`False Positive`) %>% 
  pivot_longer(`True Positive`:`False Positive`, names_to = "Group", values_to = "Value") %>% 
  group_by(Day) %>% 
  arrange(Group) %>% 
  mutate(`New Students` = sum(Value),
         Students = cumsum(Value)) %>% 
  plot_ly(x = ~Day, 
          y = ~Students, 
          color = ~Group, 
          colors = "RdYlBu",
          alpha = 0.7,
          type = "scatter",
          mode = "lines",
          fill = 'tonexty',
          text = ~paste0("</br>", Group,": ", round(Value,3),
                        "</br>Students: ", round(Students,3),
                        "</br>", Group," (Percentage of Students): ", 
                        "</br>", scales::percent(Value/`New Students`, accuracy = 0.1)), 
          hoverinfo = "text")
  
```

